name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.0.0"

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Create release branch and bump version
        env:
          REF: ${{ github.ref }}
        run: |
          echo "Full REF: ${REF}"
          REF_PART=${REF:10}
          echo "Extracted REF_PART: ${REF_PART}"
          if [ -z "$REF_PART" ] || [ "${REF_PART}" = "/" ]; then
            echo "Error: REF_PART is invalid"
            exit 1
          fi
          BRANCH=release/$REF_PART
          echo "Branch name to create: $BRANCH"
          git config --local user.email "nubledstudioetc@gmail.com"
          git config --local user.name "DashDactyl"
          git checkout -b $BRANCH
          git push -u origin $BRANCH
          sed -i "s/    'version' => 'canary',/    'version' => '${REF:11}',/" config/app.php
          git add config/app.php
          git commit -m "ci(release): bump version"
          git push

      - name: Create release archive
        run: |
          rm -rf node_modules tests CODE_OF_CONDUCT.md CONTRIBUTING.md flake.lock flake.nix phpstan.neon phpunit.xml shell.nix
          tar -czf panel.tar.gz * .editorconfig .env.example .eslintignore .eslintrc.js .gitignore .prettierrc.json

      - name: Extract changelog
        env:
          REF: ${{ github.ref }}
        run: |
          sed -n "/^## ${REF:10}/,/^## /{/^## /b;p}" CHANGELOG.md > ./RELEASE_CHANGELOG

      - name: Create checksum and add to changelog
        run: |
          SUM=$(sha256sum panel.tar.gz)
          echo -e "\n#### SHA256 Checksum\n\n\`\`\`\n$SUM\n\`\`\`\n" >> ./RELEASE_CHANGELOG
          echo $SUM > checksum.txt

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          draft: true
          prerelease: ${{ contains(github.ref, 'rc') || contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}
          body_path: ./RELEASE_CHANGELOG

      - name: Upload release archive
        id: upload-release-archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: panel.tar.gz
          asset_name: panel.tar.gz
          asset_content_type: application/gzip

      - name: Upload release checksum
        id: upload-release-checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./checksum.txt
          asset_name: checksum.txt
          asset_content_type: text/plain
